services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json

  express-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: CybersecurityRealm
      KEYCLOAK_CLIENT_ID: api-client
      KEYCLOAK_CLIENT_SECRET: mysecret
